title:            Sarang's site
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //sarangshrivastava.github.io/
#http://localhost:5000

disqus_shortname: sarang

# Owner/author information
owner:
  name:           Sarang Shrivastava
  avatar:         photo.jpg
  bio:            Currently working as an Applied NLP scientist in Research and Development Lab of Goldman Sachs . Passionate about natural language processing, machine learning, and exploring - ideas, food and places.
  email:          sarang24s@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: sarangshrivastava24
  google_scholar: YNZbKJ4AAAAJ&hl
  github: SarangShrivastava
# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
#links:
#  - title: Curriculum
#    url: /cv/
#  - title: Publications
#    url: /publications/
#  - title: Research
#    url: /research/
#  - title: Blog
#    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    India
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
